In [1]:
!pip install python-dotenv requests pandas spotipy

Requirement already satisfied: python-dotenv in /Users/bytedance/miniconda3/lib/python3.13/site-packages (1.1.0)
Requirement already satisfied: requests in /Users/bytedance/miniconda3/lib/python3.13/site-packages (2.32.5)
Requirement already satisfied: pandas in /Users/bytedance/miniconda3/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: spotipy in /Users/bytedance/miniconda3/lib/python3.13/site-packages (2.26.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from requests) (2.6.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from requests) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: redis>=3.5.3 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from spotipy) (7.4.0)
Requirement already satisfied: six>=1.5 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import os
from dotenv import load_dotenv

load_dotenv()

SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
LASTFM_API_KEY = os.getenv("LASTFM_API_KEY")
GETSONGBPM_API_KEY = os.getenv("GETSONGBPM_API_KEY")

In [3]:
!pip install spotipy pandas requests python-dotenv

Requirement already satisfied: spotipy in /Users/bytedance/miniconda3/lib/python3.13/site-packages (2.26.0)
Requirement already satisfied: pandas in /Users/bytedance/miniconda3/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: requests in /Users/bytedance/miniconda3/lib/python3.13/site-packages (2.32.5)
Requirement already satisfied: python-dotenv in /Users/bytedance/miniconda3/lib/python3.13/site-packages (1.1.0)
Requirement already satisfied: redis>=3.5.3 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from spotipy) (7.4.0)
Requirement already satisfied: urllib3>=1.26.0 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from spotipy) (2.6.1)
Requirement already satisfied: numpy>=1.26.0 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from requests) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from requests) (2026.1.4)
Requirement already satisfied: six>=1.5 in /Users/bytedance/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [18]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

# Spotify authentication
auth_manager = SpotifyClientCredentials(
    client_id=SPOTIFY_CLIENT_ID,
    client_secret=SPOTIFY_CLIENT_SECRET
)

sp = spotipy.Spotify(auth_manager=auth_manager)

# Official Spotify artist ID for Death
DEATH_ARTIST_ID = "4f5V3PQ66nIrBCqugJtaGn"

# Test artist retrieval
artist_info = sp.artist(DEATH_ARTIST_ID)

print("Artist Name:", artist_info['name'])
artist_info = sp.artist(DEATH_ARTIST_ID)

print(artist_info)

Artist Name: Death
{'external_urls': {'spotify': 'https://open.spotify.com/artist/4f5V3PQ66nIrBCqugJtaGn'}, 'href': 'https://api.spotify.com/v1/artists/4f5V3PQ66nIrBCqugJtaGn', 'id': '4f5V3PQ66nIrBCqugJtaGn', 'images': [{'url': 'https://i.scdn.co/image/b1ad9718b69b4c75164d418bde0cf3aa1566ac92', 'height': 480, 'width': 720}, {'url': 'https://i.scdn.co/image/9a0f1b399f5e272074b79f4efa3139cb2fce030e', 'height': 427, 'width': 640}, {'url': 'https://i.scdn.co/image/eb4ef3f579f7b740b56364bbb001fe03b57d8fd1', 'height': 133, 'width': 200}, {'url': 'https://i.scdn.co/image/e4a944052fabb382dd7454ee8133e93762626837', 'height': 43, 'width': 64}], 'name': 'Death', 'type': 'artist', 'uri': 'spotify:artist:4f5V3PQ66nIrBCqugJtaGn'}

In [21]:
import pandas as pd
all_albums = []

offset = 0
limit = 10

while True:
    response = sp.artist_albums(
        DEATH_ARTIST_ID,
        album_type='album',
        limit=limit,
        offset=offset
    )
    
    all_albums.extend(response['items'])
    
    if response['next'] is None:
        break
    
    offset += limit

for album in all_albums:
    print(album['name'], "|", album['release_date'])

Scream Bloody Gore (Reissue) | 2016-05-20
Scream Bloody Gore (Deluxe Reissue) | 2016-05-20
Leprosy (Deluxe Reissue) | 2014-04-29
Spiritual Healing (Deluxe Version) | 2012-11-20
Vivus! | 2012-02-28
Individual Thought Patterns (Deluxe Version) | 2011-10-25
Individual Thought Patterns | 2011-10-25
Human - Reissue | 2011-06-21
Human (Deluxe Version) | 2011-06-21
The Sound of Perserverence (Deluxe Version) | 2011-02-15
The Sound of Perseverance - Reissue | 1998
Non:Analog - On:Stage Series - Showcase Theater, CA 07-14-1995 | 1995-07-14
Non:Analog - On:Stage Series - Montreal 06-22-1995 | 1995-06-22
Symbolic (Remastered Version) | 1995-03-19
Symbolic | 1995-03-19
Non:Analog - On:Stage Series - Detroit, MI 1993 | 1993-07-07
Individual Thought Patterns (2023 Remaster) | 1993-06-22
Individual Thought Patterns | 1993
Non:Analog - On:Stage Series - Belgium 12-23-1991 | 1991-12-23
Non:Analog - On:Stage Series - 1990, 1991 Unknown | 1991-05-27
Human | 1991
Non:Analog - On:Stage Series - Tijuana 10-06-1990 | 1990-10-06
Spiritual Healing | 1990
Non:Analog - On:Stage Series - Tampa, FL 02-10-1989 | 1989-02-10
Non:Analog - On:Stage Series - New Rochelle, NY 12-03-1988 | 1988-12-03
Non:Analog - On:Stage Series - Chicago, IL 01-21-1988 | 1988-01-21
Scream Bloody Gore | 1987

In [22]:
import pandas as pd

albums_df = pd.DataFrame([
    {
        "album_name": album["name"],
        "release_date": album["release_date"],
        "total_tracks": album["total_tracks"],
        "spotify_album_id": album["id"],
        "spotify_url": album["external_urls"]["spotify"],
        "artwork_url": album["images"][0]["url"] if album["images"] else None
    }
    for album in all_albums
])

albums_df

,album_name,release_date,total_tracks,spotify_album_id,spotify_url,artwork_url
0,Scream Bloody Gore (Reissue),2016-05-20,29,29Py95CONEwzn2QCGEmY77,https://open.spotify.com/album/29Py95CONEwzn2Q...,https://i.scdn.co/image/ab67616d0000b273cc44d5...
1,Scream Bloody Gore (Deluxe Reissue),2016-05-20,43,7wMSLuSxN0v1jjDD7N06v7,https://open.spotify.com/album/7wMSLuSxN0v1jjD...,https://i.scdn.co/image/ab67616d0000b273b5a6e5...
2,Leprosy (Deluxe Reissue),2014-04-29,36,4EQcPArSq6dm0k4QWzpLBF,https://open.spotify.com/album/4EQcPArSq6dm0k4...,https://i.scdn.co/image/ab67616d0000b273437e65...
3,Spiritual Healing (Deluxe Version),2012-11-20,42,5sgSP1hx52s2KCiD2ITOfP,https://open.spotify.com/album/5sgSP1hx52s2KCi...,https://i.scdn.co/image/ab67616d0000b27306eef0...
4,Vivus!,2012-02-28,24,2t4sgPCw268I8wUHUPaUKN,https://open.spotify.com/album/2t4sgPCw268I8wU...,https://i.scdn.co/image/ab67616d0000b273e0698b...
5,Individual Thought Patterns (Deluxe Version),2011-10-25,34,3qPUKRg8S1j0V9GKA52IKe,https://open.spotify.com/album/3qPUKRg8S1j0V9G...,https://i.scdn.co/image/ab67616d0000b27364b776...
6,Individual Thought Patterns,2011-10-25,21,03AlBfN3i9KUlXbSAPmjO6,https://open.spotify.com/album/03AlBfN3i9KUlXb...,https://i.scdn.co/image/ab67616d0000b273922d2c...
7,Human - Reissue,2011-06-21,29,6uQzDrarJdqNHBTdOq7tod,https://open.spotify.com/album/6uQzDrarJdqNHBT...,https://i.scdn.co/image/ab67616d0000b273040533...
8,Human (Deluxe Version),2011-06-21,49,2bzV4j7nfY676RDSmxs0rc,https://open.spotify.com/album/2bzV4j7nfY676RD...,https://i.scdn.co/image/ab67616d0000b273383cb7...
9,The Sound of Perserverence (Deluxe Version),2011-02-15,32,5NsYXXF2RNjblJQfXZKHKQ,https://open.spotify.com/album/5NsYXXF2RNjblJQ...,https://i.scdn.co/image/ab67616d0000b273b45dc5...
10,The Sound of Perseverance - Reissue,1998,19,0p6DxsQOhQ5qiBnUu9G1PB,https://open.spotify.com/album/0p6DxsQOhQ5qiBn...,https://i.scdn.co/image/ab67616d0000b27391fcdc...
11,Non:Analog - On:Stage Series - Showcase Theate...,1995-07-14,11,1UJOH3vm7ScwjsDz77LOAR,https://open.spotify.com/album/1UJOH3vm7ScwjsD...,https://i.scdn.co/image/ab67616d0000b2731d3bd7...
12,Non:Analog - On:Stage Series - Montreal 06-22-...,1995-06-22,11,73wuhy8DKQqZph8kJdF0uG,https://open.spotify.com/album/73wuhy8DKQqZph8...,https://i.scdn.co/image/ab67616d0000b273673eca...
13,Symbolic (Remastered Version),1995-03-19,14,1QgFthItpbxvMXlgGjvhBR,https://open.spotify.com/album/1QgFthItpbxvMXl...,https://i.scdn.co/image/ab67616d0000b2739516f5...
14,Symbolic,1995-03-19,9,4YACrpVtdpoFocBPBeLbzO,https://open.spotify.com/album/4YACrpVtdpoFocB...,https://i.scdn.co/image/ab67616d0000b27370b273...
15,"Non:Analog - On:Stage Series - Detroit, MI 1993",1993-07-07,11,3nJ6LYZ83RqcDSB8RaEQv7,https://open.spotify.com/album/3nJ6LYZ83RqcDSB...,https://i.scdn.co/image/ab67616d0000b273fe15f3...
16,Individual Thought Patterns (2023 Remaster),1993-06-22,10,2Kjg65k7nGYHy4aeuutKr8,https://open.spotify.com/album/2Kjg65k7nGYHy4a...,https://i.scdn.co/image/ab67616d0000b273c8ebf1...
17,Individual Thought Patterns,1993,10,56gbykNskCFungP4TSPI2y,https://open.spotify.com/album/56gbykNskCFungP...,https://i.scdn.co/image/ab67616d0000b273ae31b2...
18,Non:Analog - On:Stage Series - Belgium 12-23-1991,1991-12-23,9,4Mrs2e6HyleqS49n1DBiZo,https://open.spotify.com/album/4Mrs2e6HyleqS49...,https://i.scdn.co/image/ab67616d0000b273d73553...
19,"Non:Analog - On:Stage Series - 1990, 1991 Unknown",1991-05-27,8,5A5dmqIoCuBAmxcocPN5MK,https://open.spotify.com/album/5A5dmqIoCuBAmxc...,https://i.scdn.co/image/ab67616d0000b2737fb3fa...
20,Human,1991,8,6AvvqTkgRqq3L4bD9qYfjD,https://open.spotify.com/album/6AvvqTkgRqq3L4b...,https://i.scdn.co/image/ab67616d0000b273102ca8...
21,Non:Analog - On:Stage Series - Tijuana 10-06-1990,1990-10-06,10,2ZMUyPmTkOala9RvTmYuO9,https://open.spotify.com/album/2ZMUyPmTkOala9R...,https://i.scdn.co/image/ab67616d0000b2730926e8...
22,Spiritual Healing,1990,24,01N3tlCCUZWmhAI73e6iid,https://open.spotify.com/album/01N3tlCCUZWmhAI...,https://i.scdn.co/image/ab67616d0000b2739b7fc6...
23,"Non:Analog - On:Stage Series - Tampa, FL 02-10...",1989-02-10,10,2StCL9DdiRf37BQ2Smqndv,https://open.spotify.com/album/2StCL9DdiRf37BQ...,https://i.scdn.co/image/ab67616d0000b273f09540...
24,"Non:Analog - On:Stage Series - New Rochelle, N...",1988-12-03,11,74DfEDeGg7TzZReYGA8VrE,https://open.spotify.com/album/74DfEDeGg7TzZRe...,https://i.scdn.co/image/ab67616d0000b273c00767...
25,"Non:Analog - On:Stage Series - Chicago, IL 01-...",1988-01-21,9,7KpWHbD2iU8smcjPggXwJm,https://open.spotify.com/album/7KpWHbD2iU8smcj...,https://i.scdn.co/image/ab67616d0000b27397d8b1...
26,Scream Bloody Gore,1987,10,0PvGbpxBh7faAVbeZM4sIm,https://open.spotify.com/album/0PvGbpxBh7faAVb...,https://i.scdn.co/image/ab67616d0000b2731a777d...

In [26]:
albums_df[["album_name", "release_date", "total_tracks", "spotify_album_id"]].sort_values("release_date")
for name in albums_df["album_name"].unique():
    print(name)

Scream Bloody Gore (Reissue)
Scream Bloody Gore (Deluxe Reissue)
Leprosy (Deluxe Reissue)
Spiritual Healing (Deluxe Version)
Vivus!
Individual Thought Patterns (Deluxe Version)
Individual Thought Patterns
Human - Reissue
Human (Deluxe Version)
The Sound of Perserverence (Deluxe Version)
The Sound of Perseverance - Reissue
Non:Analog - On:Stage Series - Showcase Theater, CA 07-14-1995
Non:Analog - On:Stage Series - Montreal 06-22-1995
Symbolic (Remastered Version)
Symbolic
Non:Analog - On:Stage Series - Detroit, MI 1993
Individual Thought Patterns (2023 Remaster)
Non:Analog - On:Stage Series - Belgium 12-23-1991
Non:Analog - On:Stage Series - 1990, 1991 Unknown
Human
Non:Analog - On:Stage Series - Tijuana 10-06-1990
Spiritual Healing
Non:Analog - On:Stage Series - Tampa, FL 02-10-1989
Non:Analog - On:Stage Series - New Rochelle, NY 12-03-1988
Non:Analog - On:Stage Series - Chicago, IL 01-21-1988
Scream Bloody Gore

In [27]:
# Studio albums

OFFICIAL_ALBUM_KEYWORDS = [
    "Scream Bloody Gore",
    "Leprosy",
    "Spiritual Healing",
    "Human",
    "Individual Thought Patterns",
    "Symbolic",
    "The Sound of Perseverance"
]

filtered_albums = []

for official_name in OFFICIAL_ALBUM_KEYWORDS:
    matches = albums_df[
        albums_df["album_name"].str.contains(official_name, case=False, regex=False)
    ].copy()
    
    if len(matches) > 0:
        # keep the earliest release date match
        best_match = matches.sort_values("release_date").iloc[0]
        filtered_albums.append(best_match)

clean_albums_df = pd.DataFrame(filtered_albums).reset_index(drop=True)

clean_albums_df

,album_name,release_date,total_tracks,spotify_album_id,spotify_url,artwork_url
0,Scream Bloody Gore,1987,10,0PvGbpxBh7faAVbeZM4sIm,https://open.spotify.com/album/0PvGbpxBh7faAVb...,https://i.scdn.co/image/ab67616d0000b2731a777d...
1,Leprosy (Deluxe Reissue),2014-04-29,36,4EQcPArSq6dm0k4QWzpLBF,https://open.spotify.com/album/4EQcPArSq6dm0k4...,https://i.scdn.co/image/ab67616d0000b273437e65...
2,Spiritual Healing,1990,24,01N3tlCCUZWmhAI73e6iid,https://open.spotify.com/album/01N3tlCCUZWmhAI...,https://i.scdn.co/image/ab67616d0000b2739b7fc6...
3,Human,1991,8,6AvvqTkgRqq3L4bD9qYfjD,https://open.spotify.com/album/6AvvqTkgRqq3L4b...,https://i.scdn.co/image/ab67616d0000b273102ca8...
4,Individual Thought Patterns,1993,10,56gbykNskCFungP4TSPI2y,https://open.spotify.com/album/56gbykNskCFungP...,https://i.scdn.co/image/ab67616d0000b273ae31b2...
5,Symbolic (Remastered Version),1995-03-19,14,1QgFthItpbxvMXlgGjvhBR,https://open.spotify.com/album/1QgFthItpbxvMXl...,https://i.scdn.co/image/ab67616d0000b2739516f5...
6,The Sound of Perseverance - Reissue,1998,19,0p6DxsQOhQ5qiBnUu9G1PB,https://open.spotify.com/album/0p6DxsQOhQ5qiBn...,https://i.scdn.co/image/ab67616d0000b27391fcdc...

In [28]:
# Orig Tracklist
ORIGINAL_TRACKLISTS = {
    "Scream Bloody Gore": [
        "Infernal Death", "Zombie Ritual", "Denial of Life", "Sacrificial",
        "Mutilation", "Regurgitated Guts", "Baptized in Blood",
        "Torn to Pieces", "Evil Dead", "Scream Bloody Gore"
    ],
    "Leprosy": [
        "Leprosy", "Born Dead", "Forgotten Past", "Left to Die",
        "Pull the Plug", "Open Casket", "Primitive Ways", "Choke on It"
    ],
    "Spiritual Healing": [
        "Living Monstrosity", "Altering the Future", "Defensive Personalities",
        "Within the Mind", "Spiritual Healing", "Low Life", "Genetic Reconstruction",
        "Killing Spree"
    ],
    "Human": [
        "Flattening of Emotions", "Suicide Machine", "Together as One",
        "Secret Face", "Lack of Comprehension", "See Through Dreams",
        "Cosmic Sea", "Vacant Planets"
    ],
    "Individual Thought Patterns": [
        "Overactive Imagination", "In Human Form", "Jealousy", "Trapped in a Corner",
        "Nothing Is Everything", "Mentally Blind", "Individual Thought Patterns",
        "Destiny", "Out of Touch", "The Philosopher"
    ],
    "Symbolic": [
        "Symbolic", "Zero Tolerance", "Empty Words", "Sacred Serenity",
        "1,000 Eyes", "Without Judgement", "Crystal Mountain",
        "Misanthrope", "Perennial Quest"
    ],
    "The Sound of Perseverance": [
        "Scavenger of Human Sorrow", "Bite the Pain", "Spirit Crusher",
        "Story to Tell", "Flesh and the Power It Holds", "Voice of the Soul",
        "To Forgive Is to Suffer", "A Moment of Clarity", "Painkiller"
    ]
}

In [32]:
tracks_data = []

for _, row in clean_albums_df.iterrows():
    
    album_id = row["spotify_album_id"]
    album_name = row["album_name"]
    release_date = row["release_date"]
    artwork_url = row["artwork_url"]
    
    tracks = sp.album_tracks(album_id)
    
    for track in tracks["items"]:
        
        tracks_data.append({
            "album_name": album_name,
            "release_date": release_date,
            "artwork_url": artwork_url,
            "track_name": track["name"],
            "track_number": track["track_number"],
            "duration_ms": track["duration_ms"],
            "spotify_track_id": track["id"]
        })

tracks_df = pd.DataFrame(tracks_data)

tracks_df.head()

,album_name,release_date,artwork_url,track_name,track_number,duration_ms,spotify_track_id
0,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Infernal Death,1,173720,6w6ixHfMEbfSC7X3awzbok
1,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Zombie Ritual,2,273413,4K3qzy3AR3Lo02ybxs90gW
2,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Denial of Life,3,215226,3SypDWp8cRyXemFer9dQuH
3,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Sacrificial,4,221706,6TtwlRtSSr0f2O97Uh3hSe
4,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Mutilation,5,208000,4MIM3WVaGRVvzNmrI2AGqY

In [33]:
# Only original tracks
clean_tracks = []

for album_name, official_tracks in ORIGINAL_TRACKLISTS.items():
    album_tracks = tracks_df[
        tracks_df["album_name"].str.contains(album_name, case=False, regex=False)
    ].copy()
    
    for track_position, official_track in enumerate(official_tracks, start=1):
        match = album_tracks[
            album_tracks["track_name"].str.lower().str.strip() == official_track.lower().strip()
        ]
        
        if len(match) > 0:
            selected = match.iloc[0].copy()
            selected["official_track_number"] = track_position
            selected["official_track_name"] = official_track
            clean_tracks.append(selected)
        else:
            print(f"Missing track: {album_name} - {official_track}")

clean_tracks_df = pd.DataFrame(clean_tracks)

clean_tracks_df = clean_tracks_df.sort_values(
    ["release_date", "official_track_number"]
).reset_index(drop=True)

clean_tracks_df

,album_name,release_date,artwork_url,track_name,track_number,duration_ms,spotify_track_id,official_track_number,official_track_name
0,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Infernal Death,1,173720,6w6ixHfMEbfSC7X3awzbok,1,Infernal Death
1,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Zombie Ritual,2,273413,4K3qzy3AR3Lo02ybxs90gW,2,Zombie Ritual
2,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Denial of Life,3,215226,3SypDWp8cRyXemFer9dQuH,3,Denial of Life
3,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Sacrificial,4,221706,6TtwlRtSSr0f2O97Uh3hSe,4,Sacrificial
4,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Mutilation,5,208000,4MIM3WVaGRVvzNmrI2AGqY,5,Mutilation
...,...,...,...,...,...,...,...,...,...
57,Leprosy (Deluxe Reissue),2014-04-29,https://i.scdn.co/image/ab67616d0000b273437e65...,Left to Die,4,277373,0BO5g7FXNhZgQuC8xIORDm,4,Left to Die
58,Leprosy (Deluxe Reissue),2014-04-29,https://i.scdn.co/image/ab67616d0000b273437e65...,Pull the Plug,5,266773,2l0h4aBFLp9HdoaNdCTlbW,5,Pull the Plug
59,Leprosy (Deluxe Reissue),2014-04-29,https://i.scdn.co/image/ab67616d0000b273437e65...,Open Casket,6,295693,4E1dHrIMIXybxs9DqguLyZ,6,Open Casket
60,Leprosy (Deluxe Reissue),2014-04-29,https://i.scdn.co/image/ab67616d0000b273437e65...,Primitive Ways,7,273533,5S2zI4ZD15GtrC4MHoKTqy,7,Primitive Ways
61,Leprosy (Deluxe Reissue),2014-04-29,https://i.scdn.co/image/ab67616d0000b273437e65...,Choke on It,8,355213,3iRcqSKMnnB3bmZlpeL8eP,8,Choke on It

In [34]:
# Checking
clean_tracks_df.groupby("album_name")["official_track_name"].count()
clean_tracks_df.shape

(62, 9)

In [35]:
# Save CSV
clean_albums_df.to_csv("death_clean_albums.csv", index=False)
clean_tracks_df.to_csv("death_clean_tracks.csv", index=False)

In [38]:
### Listeners data
import requests
import time

def get_lastfm_track_info(artist, track):
    url = "http://ws.audioscrobbler.com/2.0/"
    
    params = {
        "method": "track.getInfo",
        "api_key": LASTFM_API_KEY,
        "artist": artist,
        "track": track,
        "format": "json"
    }
    
    response = requests.get(url, params=params)
    data = response.json()
    
    if "track" in data:
        return {
            "lastfm_track_listeners": data["track"].get("listeners"),
            "lastfm_track_playcount": data["track"].get("playcount")
        }
    
    return {
        "lastfm_track_listeners": None,
        "lastfm_track_playcount": None
    }

In [44]:
lastfm_track_data = []

for _, row in clean_tracks_df.iterrows():
    info = get_lastfm_track_info("Death", row["official_track_name"])
    
    lastfm_track_data.append(info)
    
    time.sleep(0.25)

lastfm_track_df = pd.DataFrame(lastfm_track_data)

clean_tracks_df = pd.concat(
    [clean_tracks_df.reset_index(drop=True), lastfm_track_df],
    axis=1
)

clean_tracks_df.head()
clean_tracks_df.to_csv("death_tracks_with_lastfm.csv", index=False)

In [41]:
clean_tracks_df.columns

Index(['album_name', 'release_date', 'artwork_url', 'track_name',
       'track_number', 'duration_ms', 'spotify_track_id',
       'official_track_number', 'official_track_name',
       'lastfm_track_listeners', 'lastfm_track_playcount',
       'lastfm_track_listeners', 'lastfm_track_playcount',
       'lastfm_track_listeners', 'lastfm_track_playcount'],
      dtype='str')

In [51]:
!pip install musicbrainzngs

Requirement already satisfied: musicbrainzngs in /Users/bytedance/miniconda3/lib/python3.13/site-packages (0.7.1)

In [53]:
import musicbrainzngs
import requests
import time
import pandas as pd

musicbrainzngs.set_useragent(
    "death-dashboard-project",
    "1.0",
    "macob39@example.com"
)

In [54]:
def get_musicbrainz_recording_id(artist, track):
    try:
        result = musicbrainzngs.search_recordings(
            artist=artist,
            recording=track,
            limit=5
        )
        
        recordings = result.get("recording-list", [])
        
        if len(recordings) > 0:
            return recordings[0]["id"]
        
        return None
    
    except Exception as e:
        print(f"MusicBrainz error for {track}: {e}")
        return None

In [55]:
def get_acousticbrainz_bpm(mbid):
    if pd.isna(mbid):
        return None
    
    url = f"https://acousticbrainz.org/api/v1/{mbid}/low-level"
    
    try:
        response = requests.get(url, timeout=10)
        
        if response.status_code != 200:
            return None
        
        data = response.json()
        
        bpm = data.get("rhythm", {}).get("bpm")
        return bpm
    
    except Exception as e:
        print(f"AcousticBrainz error for {mbid}: {e}")
        return None

In [56]:
musicbrainz_ids = []
bpm_values = []

for _, row in clean_tracks_df.iterrows():
    track_name = row["official_track_name"]
    
    mbid = get_musicbrainz_recording_id("Death", track_name)
    musicbrainz_ids.append(mbid)
    
    bpm = get_acousticbrainz_bpm(mbid)
    bpm_values.append(bpm)
    
    time.sleep(1.2)

clean_tracks_df["musicbrainz_recording_id"] = musicbrainz_ids
clean_tracks_df["bpm"] = bpm_values

In [61]:
clean_tracks_df[
    ["album_name", "official_track_name", "musicbrainz_recording_id", "bpm"]
].head(20)

,album_name,official_track_name,musicbrainz_recording_id,bpm
0,Scream Bloody Gore,Infernal Death,5bc83118-0a1a-4bf6-9be5-9c491ea7a13f,NaN
1,Scream Bloody Gore,Zombie Ritual,8b0fc9fb-1bce-452f-a3a5-0670af2cf101,128.498871
2,Scream Bloody Gore,Denial of Life,44db3fcd-a9f1-4687-b280-d250535cec69,154.998199
3,Scream Bloody Gore,Sacrificial,56ae6282-0452-43e5-9a64-3db82a847976,142.773468
4,Scream Bloody Gore,Mutilation,44c962ad-944d-48cd-ae95-6bcac795e333,109.944084
5,Scream Bloody Gore,Regurgitated Guts,f0bbcd48-f1c7-44f8-8028-21f805bb4c89,90.449341
6,Scream Bloody Gore,Baptized in Blood,9adb7449-13c2-4a32-86b6-69824ee9982f,NaN
7,Scream Bloody Gore,Torn to Pieces,2b60afdb-6c7a-4af3-9bd3-37b0335360fb,NaN
8,Scream Bloody Gore,Evil Dead,cd5caf63-fd4b-4dd0-87d1-3a9c4057e76e,NaN
9,Scream Bloody Gore,Scream Bloody Gore,0c38eac3-e2ff-4002-9eeb-864b8e440c52,NaN
10,Spiritual Healing,Living Monstrosity,801f6ed7-6598-4c1a-9f31-ee3fffa5e6d1,129.134293
11,Spiritual Healing,Altering the Future,9cc95ba0-5453-4ca0-9dd4-beaead9db4d4,154.519089
12,Spiritual Healing,Defensive Personalities,bd9f27e2-050d-4c49-b581-850fa0384083,142.644867
13,Spiritual Healing,Within the Mind,3f498890-4034-4835-8f75-c0a23feabf45,172.265015
14,Spiritual Healing,Spiritual Healing,8285138a-5a31-4a1f-aa23-876a91637a2c,165.775177
15,Spiritual Healing,Low Life,ee311e66-1a6f-428e-8ea3-4539e48b291f,132.202499
16,Spiritual Healing,Genetic Reconstruction,0c38b81c-8fd4-4abe-8b75-ea5f770fbac2,132.403107
17,Spiritual Healing,Killing Spree,2663a1f3-e560-4316-b872-6fde09136b1b,129.224747
18,Human,Flattening of Emotions,254c5295-707f-48d3-b2eb-65cfd7aa4922,103.937828
19,Human,Suicide Machine,869981d6-3639-4038-abe0-17473f0d2d54,NaN

In [60]:
clean_tracks_df["bpm"].isna().sum()

np.int64(20)

In [62]:
missing_bpm_df = clean_tracks_df[
    clean_tracks_df["bpm"].isna()
][["album_name", "official_track_name", "musicbrainz_recording_id"]]

missing_bpm_df

,album_name,official_track_name,musicbrainz_recording_id
0,Scream Bloody Gore,Infernal Death,5bc83118-0a1a-4bf6-9be5-9c491ea7a13f
6,Scream Bloody Gore,Baptized in Blood,9adb7449-13c2-4a32-86b6-69824ee9982f
7,Scream Bloody Gore,Torn to Pieces,2b60afdb-6c7a-4af3-9bd3-37b0335360fb
8,Scream Bloody Gore,Evil Dead,cd5caf63-fd4b-4dd0-87d1-3a9c4057e76e
9,Scream Bloody Gore,Scream Bloody Gore,0c38eac3-e2ff-4002-9eeb-864b8e440c52
19,Human,Suicide Machine,869981d6-3639-4038-abe0-17473f0d2d54
26,Individual Thought Patterns,Overactive Imagination,f545c58c-7465-4fd2-a67b-58d4f4644286
27,Individual Thought Patterns,In Human Form,89996b98-c79b-44d5-885e-15667a7297df
28,Individual Thought Patterns,Jealousy,9c129ff2-5dba-434b-9e3e-0a58310d8b60
30,Individual Thought Patterns,Nothing Is Everything,624191e4-1a95-4034-8cff-4b27437d0f61
32,Individual Thought Patterns,Individual Thought Patterns,612ed956-0356-46f6-8e97-7943790ec9a1
33,Individual Thought Patterns,Destiny,0657c0a7-6ad5-4a48-a686-8d5b66d3364b
34,Individual Thought Patterns,Out of Touch,f50bf759-2e12-4910-adb5-e88811f7292a
35,Individual Thought Patterns,The Philosopher,772843b1-f455-469d-a606-28052dc47ac9
38,Symbolic (Remastered Version),Empty Words,8488987c-2d71-47ae-bf88-4be2a5879d83
45,The Sound of Perseverance - Reissue,Scavenger of Human Sorrow,d87b585b-ecd9-483b-80e4-63a7ca257b13
47,The Sound of Perseverance - Reissue,Spirit Crusher,3f2b1899-1633-499b-8640-f4a5680dc7b9
54,Leprosy (Deluxe Reissue),Leprosy,9900bd7e-fc45-4512-9a19-adb5d20f376b
55,Leprosy (Deluxe Reissue),Born Dead,6c08eeef-3d59-49df-99e0-ebcd53579918
59,Leprosy (Deluxe Reissue),Open Casket,0aa9e7b3-a351-441a-8208-79ccd3bc8f91

In [63]:
clean_tracks_df.to_csv("death_tracks_final.csv", index=False)

In [66]:
import pandas as pd

death_df = pd.read_csv("death_tracks_final.csv")

death_df.head()

,album_name,release_date,artwork_url,track_name,track_number,duration_ms,spotify_track_id,official_track_number,official_track_name,lastfm_track_listeners,lastfm_track_playcount,lastfm_track_listeners.1,lastfm_track_playcount.1,lastfm_track_listeners.2,lastfm_track_playcount.2,lastfm_track_listeners.3,lastfm_track_playcount.3,musicbrainz_recording_id,bpm
0,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Infernal Death,1,173720,6w6ixHfMEbfSC7X3awzbok,1,Infernal Death,178672,1058324,178672,1058324,178672,1058324,178672,1058324,5bc83118-0a1a-4bf6-9be5-9c491ea7a13f,106.000000
1,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Zombie Ritual,2,273413,4K3qzy3AR3Lo02ybxs90gW,2,Zombie Ritual,176771,1277926,176771,1277926,176771,1277926,176771,1277926,8b0fc9fb-1bce-452f-a3a5-0670af2cf101,128.498871
2,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Denial of Life,3,215226,3SypDWp8cRyXemFer9dQuH,3,Denial of Life,135465,704079,135465,704079,135465,704079,135465,704079,44db3fcd-a9f1-4687-b280-d250535cec69,154.998199
3,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Sacrificial,4,221706,6TtwlRtSSr0f2O97Uh3hSe,4,Sacrificial,126781,637101,126781,637101,126781,637101,126781,637101,56ae6282-0452-43e5-9a64-3db82a847976,142.773468
4,Scream Bloody Gore,1987,https://i.scdn.co/image/ab67616d0000b2731a777d...,Mutilation,5,208000,4MIM3WVaGRVvzNmrI2AGqY,5,Mutilation,128545,680027,128545,680027,128545,680027,128545,680027,44c962ad-944d-48cd-ae95-6bcac795e333,109.944084

In [69]:
death_df.columns

Index(['album_name', 'release_date', 'artwork_url', 'track_name',
       'track_number', 'duration_ms', 'spotify_track_id',
       'official_track_number', 'official_track_name',
       'lastfm_track_listeners', 'lastfm_track_playcount',
       'lastfm_track_listeners.1', 'lastfm_track_playcount.1',
       'lastfm_track_listeners.2', 'lastfm_track_playcount.2',
       'lastfm_track_listeners.3', 'lastfm_track_playcount.3',
       'musicbrainz_recording_id', 'bpm'],
      dtype='str')